"""empty message

Revision ID: 8bf52d893273
Revises: 5f0ce7ef8edd
Create Date: 2023-05-06 20:44:29.606611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bf52d893273'
down_revision = '5f0ce7ef8edd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rubrics_variants_rubric_id_fkey', 'rubrics_variants', type_='foreignkey')
    op.create_foreign_key(None, 'rubrics_variants', 'rubrics', ['rubric_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rubrics_variants', type_='foreignkey')
    op.create_foreign_key('rubrics_variants_rubric_id_fkey', 'rubrics_variants', 'rubric_sections', ['rubric_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
