"""empty message

Revision ID: a8ef792817f0
Revises: c8dcd93cab7d
Create Date: 2023-06-04 21:22:23.783106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ef792817f0'
down_revision = 'c8dcd93cab7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
